#encoding utf-8
# also notice the call to 'freeze'
#default

COMMENTS_COOLDOWM_INTERVAL = 120
COMMENTS_COOLDOWM_LIMIT = 3
REGISTRATION_COOLDOWM_INTERVAL = 1
REGISTRATION_COOLDOWM_LIMIT = 3

GLOBAL_INPUT_MAX_LENGTH = 10000

AVATAR_THUMB_WIDTH = 48
AVATAR_THUMB_HEIGHT = 48
AVATAR_PROFILE_WIDTH = 100
AVATAR_PROFILE_HEIGHT = 100
AVATAR_LARGE_WIDTH = 500
AVATAR_LARGE_HEIGHT = 500

ACCECPTED_IMAGES = 'image/png,image/gif,image/jpg,image/jpeg'
GENERAL_TIME_FORMAT = "%m-%d %H:%M"
VALID_URL_FORMAT = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
