development:
  adapter: postgresql
  encoding: unicode
  database: dionysus_development
  pool: 5
  username: dionysus
  password: dionysus

production:
  adapter: postgresql
  encoding: unicode
  database: dionysus_production
  pool: 5
  username: dionysus
  password: dionysus
